id: I68585C46
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-30T00:16:58+00:00'
last_modified: '2022-06-08T13:26:34.741510+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W00KG03599
  title: ཀན་ལྷོ་ཁུལ་གྱི་བོན་དགོན་ལོ་རྒྱུས་མདོར་བསྡུས་
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    B2C5:
      image_group_id: I00KG03618
      title: Volume 1 of kan lho khul gyi bon dgon lo rgyus mdor bsdus
      total_pages: 132
      order: 1
      base_file: B2C5.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
