id: P007032
initial_creation_type: ocr
created_at: 30/03/2020
last_modified_at: 2021-12-17 12:37:24.796369
source_metadata:
  id: bdr:W00KG03599
  title: ཀན་ལྷོ་ཁུལ་གྱི་བོན་དགོན་ལོ་རྒྱུས་མདོར་བསྡུས་
  author: ''
  volumes:
    497431451d09440eb3ba640ee168c5b3:
      image_group_id: I00KG03618
      title: Volume 1 of kan lho khul gyi bon dgon lo rgyus mdor bsdus
      volume_number: 1
      total_pages: 132
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
