id: P007032
initial_creation_type: ocr
source_metadata:
  id: bdr:W00KG03599
  title: ཀན་ལྷོ་ཁུལ་གྱི་བོན་དགོན་ལོ་རྒྱུས་མདོར་བསྡུས་
  author: ''
  volumes:
    a23ee45d43944cb6ad1962867a232a88:
      image_group_id: I00KG03618
      title: ''
      volume_number: 1
      total_pages: 132
ebook_metadata:
  title: ཀན་ལྷོ་ཁུལ་གྱི་བོན་དགོན་ལོ་རྒྱུས་མདོར་བསྡུས་
  author: ''
  sku: P007032
  cover: cover.jpg
  layers:
  - pagination
